---
Name: image-placeholders
---

SilverStripe\Assets\File:
  extensions:
    Innoweb\ImagePlaceholders\ImageExtension

SilverStripe\Assets\Storage\DBFile:
  extensions:
    Innoweb\ImagePlaceholders\ImageExtension
